### ISSUE TITLE
feature/add-patient-specimen-metric

### ISSUE THREAD

**Issue by bwalsh** [gks-anvil/vrs_anvil_toolkit#44]
As a vrs analyst, when I'm creating a figure, it would be useful to know what specimen or patient had a metakb hit.

(Note: this is a secondary item, please consider working on it when other items complete )

**Comment by quinnwai** [comment]
potentially generalizing the use case to non-specimens, I want to know which line of a VCF file had a metakb hit

**Comment by quinnwai** [comment]
Reasoning in #37, but in short, line number is not coupled with the data in the VCF and line numbers can be changed by editing the file. We instead are storing the gnomad expression related to a metakb hit since it contains the coordinate info to reference. See `scripts/1000g-sample-stats.py` in #56 for implementation

**Comment by quinnwai** [comment]
@bwalsh to close if that makes sense

**Comment by bwalsh** [comment]
See #66 for more details.
